# Generated by Django 4.2.1 on 2023-06-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
