# Generated by Django 4.2.1 on 2023-06-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_review_text_review_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
