# Generated by Django 4.2.1 on 2023-06-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='display_comments',
            field=models.BooleanField(default=True),
        ),
    ]
