# Generated by Django 4.2.1 on 2023-06-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_book_display_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
