# Generated by Django 4.2.1 on 2023-06-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
