# Generated by Django 4.2.1 on 2023-06-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
