# Generated by Django 4.2.1 on 2023-06-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_review_last_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
