# Generated by Django 4.2.1 on 2023-06-21 03:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_rename_dislike_reviewdislike_rename_like_reviewlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewdislike',
            unique_together={('review', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('review', 'user')},
        ),
    ]
