# Generated by Django 4.2.1 on 2023-06-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_reviewdislike_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes_count',
        ),
    ]
