# Generated by Django 4.2.1 on 2023-06-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_review_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
