# Generated by Django 4.2.1 on 2023-06-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
