# Generated by Django 4.2.1 on 2023-06-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdislike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_dislikes', to='store.review'),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='store.review'),
        ),
    ]
