# Generated by Django 4.2.1 on 2023-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_reviewdislike_review_alter_reviewlike_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylibrary',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='finished_library', to='store.book'),
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='reading',
            field=models.ManyToManyField(blank=True, related_name='reading_library', to='store.book'),
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_library', to='store.book'),
        ),
    ]
