# Generated by Django 4.2.1 on 2023-06-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_mylibrary_finished_mylibrary_reading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLibrary',
        ),
    ]
