# Generated by Django 4.2.1 on 2023-07-16 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_mylibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='writer',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='totalrating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='totalreview',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('epic_novel', 'Epic Novel'), ('novel', 'Novel'), ('short_story', 'Short Story'), ('short_story_collection', 'Short Story Collection'), ('poem_collection', 'Poem Collection')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.series'),
        ),
    ]
