# Generated by Django 4.2.1 on 2023-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_book_co_author_alter_book_author_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_remark',
            field=models.TextField(blank=True),
        ),
    ]
