# Generated by Django 4.2.1 on 2023-07-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_series_author'),
        ('store', '0035_series_author_remark_series_description_and_more'),
    ]

    operations = [
    ]
