# Generated by Django 4.2.1 on 2023-07-20 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0038_alter_series_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='co_author2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthored_books2', to=settings.AUTH_USER_MODEL),
        ),
    ]
