# Generated by Django 4.2.1 on 2023-07-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_book_co_author2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.ImageField(default='default_book_img.png', upload_to='static/images/coverpage'),
        ),
    ]
