# Generated by Django 4.2.1 on 2023-07-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='order',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
