# Generated by Django 4.2.1 on 2023-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_chapter_order_alter_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='additional_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
