# Generated by Django 4.2.1 on 2023-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_bookupvote_bookdownvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
