# Generated by Django 4.2.1 on 2023-11-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_book_author_alter_series_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subgenres',
            field=models.ManyToManyField(blank=True, related_name='subgenres', to='store.genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='child_subgenres', to='store.genre'),
        ),
    ]
