# Generated by Django 4.2.1 on 2023-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_book_subgenres_genre_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, help_text='The number of the book in the series', null=True),
        ),
    ]
