# Generated by Django 4.2.7 on 2023-11-20 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_reviewview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookview',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
