# Generated by Django 4.2.7 on 2023-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_bookview_last_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookview',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='bookview',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
