# Generated by Django 4.2.7 on 2023-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_alter_bookview_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
