# Generated by Django 4.2.7 on 2023-11-22 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0065_alter_bookview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.review'),
        ),
        migrations.AlterField(
            model_name='reviewview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
