# Generated by Django 4.2.7 on 2023-11-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_reviewview_ip_address_alter_reviewview_review_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewview',
            unique_together=set(),
        ),
    ]
