# Generated by Django 4.2.7 on 2023-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
