# Generated by Django 4.2.7 on 2023-12-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_chapter_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdislike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='store.comment'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.comment'),
        ),
    ]
