# Generated by Django 4.2.7 on 2024-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
