# Generated by Django 4.2.7 on 2024-01-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
