# Generated by Django 4.2.1 on 2024-02-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_userbookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='in_draft', max_length=100),
        ),
    ]
