# Generated by Django 4.2.1 on 2024-02-22 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0080_remove_chapter_status_chapter_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('note_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='store.chapter')),
            ],
        ),
    ]
