# Generated by Django 4.2.1 on 2024-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('epic_novel', 'Epic Novel'), ('novel', 'Novel'), ('short_story_poem', 'Short Story / Poem'), ('collection', 'Short Story Collection / Poem Collection')], max_length=50),
        ),
    ]
