# Generated by Django 4.2.1 on 2024-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_book_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_remark',
        ),
    ]
