# Generated by Django 4.2.1 on 2024-03-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_alter_book_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors_note',
            field=models.TextField(blank=True),
        ),
    ]
