# Generated by Django 4.2.1 on 2024-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_book_authors_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('friends', 'Friends only')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='download_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('friends', 'Friends only')], default='public', max_length=20),
        ),
    ]
