# Generated by Django 4.2.1 on 2024-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_book_comment_access_book_download_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('friends', 'Friends only'), ('followers_friends', 'Followers and Friends')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('friends', 'Friends only'), ('followers_friends', 'Followers and Friends')], default='public', max_length=20),
        ),
    ]
