# Generated by Django 4.2.1 on 2024-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_alter_book_comment_access_alter_book_download_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('followers', 'Followers')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_access',
            field=models.CharField(choices=[('public', 'Everyone'), ('private', 'No one'), ('followers', 'Followers')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=10),
        ),
    ]
