# Generated by Django 4.2.1 on 2024-03-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_alter_book_comment_access_alter_book_download_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default='Undefined', on_delete=django.db.models.deletion.CASCADE, to='store.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='private', max_length=10),
        ),
    ]
