# Generated by Django 4.2.1 on 2024-03-27 23:21

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_book_demo_version_alter_book_authors_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=store.models.Book.get_undefined_genre, on_delete=django.db.models.deletion.CASCADE, to='store.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
