# Generated by Django 4.2.1 on 2024-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_alter_book_genre_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='volume_number',
            field=models.PositiveIntegerField(default=1, help_text='The number of the book in the series'),
        ),
    ]
