# Generated by Django 4.2.1 on 2024-03-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0099_alter_book_volume_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='Book Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume_number',
            field=models.PositiveIntegerField(default=1, help_text='The number of the book in the series'),
        ),
    ]
