# Generated by Django 4.2.1 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
