# Generated by Django 4.2.1 on 2024-03-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_illustration_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illustration',
            old_name='title',
            new_name='description',
        ),
    ]
