# Generated by Django 4.2.1 on 2024-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0105_rename_title_illustration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='description',
            field=models.CharField(default='Illustration Descrpition', max_length=255),
        ),
    ]
