# Generated by Django 4.2.1 on 2024-04-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0106_alter_illustration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('published', 'Published'), ('uploaded', 'Uploaded'), ('changed', 'Changed')], default='created', max_length=20),
        ),
    ]
