# Generated by Django 4.2.1 on 2024-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0107_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='use_for_library_cover',
            field=models.BooleanField(default=False, help_text='Use the left side of the picture for the library book cover'),
        ),
    ]
