# Generated by Django 4.2.1 on 2024-04-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0110_alter_bookfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
