# Generated by Django 4.2.1 on 2024-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0113_vote_delete_booklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
