# Generated by Django 4.2.1 on 2024-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_about_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='library_visibility',
            field=models.CharField(choices=[('private', 'Private'), ('followers', 'Followers'), ('everyone', 'Everyone')], default='everyone', max_length=10),
        ),
    ]
