# Generated by Django 4.2.1 on 2024-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_library_visibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illustration',
        ),
    ]
