# Generated by Django 4.2.1 on 2024-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notificationsetting_library_favourite_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookchapternotification',
            name='chapter_count_at_last_notification',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
