# Generated by Django 4.2.1 on 2024-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_notification_message_notification_message1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message2',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
