# Generated by Django 4.2.1 on 2024-04-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_notification_message1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='book_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
