# Generated by Django 4.2.1 on 2024-10-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryRegistration',
        ),
    ]
