# Generated by Django 4.2.1 on 2024-11-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_delete_temporarypasswordstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalReaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('sepia', 'Sepia')], default='sepia', max_length=10)),
                ('font_size', models.IntegerField(default=1)),
                ('line_height', models.IntegerField(default=1)),
                ('text_position', models.IntegerField(default=1)),
                ('font_weight', models.IntegerField(default=1)),
                ('font', models.IntegerField(default=1)),
                ('last_page', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
