# Generated by Django 4.2.1 on 2024-11-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_personalreadersettings_last_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalReaderSettings',
        ),
    ]
