# Generated by Django 4.2.1 on 2024-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_personalreadersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalreadersettings',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('sepia', 'Sepia')], default='sepia', max_length=10),
        ),
    ]
