# Generated by Django 4.2.1 on 2024-11-07 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_alter_personalreadersettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMainPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_theme', models.CharField(default='default_theme', max_length=100)),
                ('show_first_books', models.BooleanField(default=False)),
                ('show_only_free_books', models.BooleanField(default=False)),
                ('restricted_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
