# Generated by Django 4.2.1 on 2024-11-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_usermainpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermainpagesettings',
            name='view_mode',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermainpagesettings',
            name='main_page_theme',
            field=models.CharField(choices=[('default_theme', 'Default Theme'), ('white_theme', 'White Theme')], default='default_theme', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermainpagesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
