# Generated by Django 4.2.1 on 2024-11-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0028_passwordchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_reading', models.BooleanField(default=True)),
                ('notify_liked', models.BooleanField(default=True)),
                ('notify_wishlist', models.BooleanField(default=True)),
                ('notify_favorites', models.BooleanField(default=True)),
                ('chapter_notification_threshold', models.IntegerField(choices=[(1, '1 Chapter'), (3, '3 Chapters'), (5, '5 Chapters'), (10, '10 Chapters'), (30, '30 Chapters')], default=1)),
                ('group_by_author', models.BooleanField(default=True)),
                ('show_author_updates', models.BooleanField(default=True)),
                ('newbooks', models.BooleanField(default=False)),
                ('library_reading_updates', models.BooleanField(default=True)),
                ('library_wishlist_updates', models.BooleanField(default=True)),
                ('library_liked_updates', models.BooleanField(default=True)),
                ('library_favourite_updates', models.BooleanField(default=False)),
                ('show_review_updates', models.BooleanField(default=True)),
                ('show_comment_updates', models.BooleanField(default=True)),
                ('show_follower_updates', models.BooleanField(default=True)),
                ('show_response_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersnotificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
        migrations.DeleteModel(
            name='UsersNotificationSettings',
        ),
    ]
