# Generated by Django 4.2.1 on 2024-11-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_notificationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='notify_favorites',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='notify_liked',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='notify_reading',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='notify_wishlist',
        ),
    ]
